---
abstract: "Pure Perl implementation of MongoDB's BSON serialization"
author:
  - 'minimalist <minimalist@lavabit.com>'
build_requires:
  DateTime: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BSON
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Test::More: 0
  Tie::IxHash: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/naturalist/Perl-BSON/issues
  repository: git://github.com/naturalist/Perl-BSON.git
version: 0.05
